name: build readme

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2.1.1

    - name: Install Python dependencies
      run: python -m pip install requests lxml

    - name: Run python
      run: python generateReadme.py

    - name: Record time
      run: echo `date` > date.log

    - name: Commit and push if changed
      run: |
        git config --global user.email "xindoo@zxs.io"
        git config --global user.name "zxs"
        git add README.md
        git diff --quiet || git commit -m "Updated Readme" 
        git push
